version: "3"
services:
  couchdb:
    image: couchdb:2.3.1
    ports:
      - 5984:5984
    volumes:
      - ./db/couchdb/data:/opt/couchdb/data
      - ./db/couchdb/etc:/opt/couchdb/etc/local.d
    networks:
      web-net:

  web:
    build: ./project
    volumes:
      - ./project:/project
    ports:
      - 5000:5000
    depends_on:
      - couchdb
    networks:
      - web-net

networks:
  web-net: