version: "3"
services:
  streamharvester:
    build: streamharvester
    volumes:
      - ./streamharvester:/streamharvester
    network_mode: "host"    
  timelineharvester:
    build: timelineharvester
    volumes:
      - ./timelineharvester:/timelineharvester
    network_mode: "host"
  api:
    build: api
    volumes:
      - ./api:/api
    ports:
      - 5000:5000
    networks:
      - web-net
  client:
    build: client
    volumes:
      - ./client:/usr/src/app
      - ./client/node_modules:/usr/src/app/node_modules
    ports:
      - 80:3000
    networks:
      - web-net

networks:
  web-net:
